/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesAutocompleteSplatRouteImport } from './routes/places-autocomplete/$'
import { Route as PaymentCardIconsSplatRouteImport } from './routes/payment-card-icons/$'
import { Route as InputTagSplatRouteImport } from './routes/input-tag/$'
import { Route as AppOnboardSplatRouteImport } from './routes/app-onboard/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesAutocompleteSplatRoute = PlacesAutocompleteSplatRouteImport.update({
  id: '/places-autocomplete/$',
  path: '/places-autocomplete/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCardIconsSplatRoute = PaymentCardIconsSplatRouteImport.update({
  id: '/payment-card-icons/$',
  path: '/payment-card-icons/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InputTagSplatRoute = InputTagSplatRouteImport.update({
  id: '/input-tag/$',
  path: '/input-tag/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardSplatRoute = AppOnboardSplatRouteImport.update({
  id: '/app-onboard/$',
  path: '/app-onboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/app-onboard/$': typeof AppOnboardSplatRoute
  '/input-tag/$': typeof InputTagSplatRoute
  '/payment-card-icons/$': typeof PaymentCardIconsSplatRoute
  '/places-autocomplete/$': typeof PlacesAutocompleteSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/app-onboard/$': typeof AppOnboardSplatRoute
  '/input-tag/$': typeof InputTagSplatRoute
  '/payment-card-icons/$': typeof PaymentCardIconsSplatRoute
  '/places-autocomplete/$': typeof PlacesAutocompleteSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/chat': typeof ApiChatRoute
  '/api/search': typeof ApiSearchRoute
  '/app-onboard/$': typeof AppOnboardSplatRoute
  '/input-tag/$': typeof InputTagSplatRoute
  '/payment-card-icons/$': typeof PaymentCardIconsSplatRoute
  '/places-autocomplete/$': typeof PlacesAutocompleteSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/chat'
    | '/api/search'
    | '/app-onboard/$'
    | '/input-tag/$'
    | '/payment-card-icons/$'
    | '/places-autocomplete/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/chat'
    | '/api/search'
    | '/app-onboard/$'
    | '/input-tag/$'
    | '/payment-card-icons/$'
    | '/places-autocomplete/$'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/chat'
    | '/api/search'
    | '/app-onboard/$'
    | '/input-tag/$'
    | '/payment-card-icons/$'
    | '/places-autocomplete/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  AppOnboardSplatRoute: typeof AppOnboardSplatRoute
  InputTagSplatRoute: typeof InputTagSplatRoute
  PaymentCardIconsSplatRoute: typeof PaymentCardIconsSplatRoute
  PlacesAutocompleteSplatRoute: typeof PlacesAutocompleteSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places-autocomplete/$': {
      id: '/places-autocomplete/$'
      path: '/places-autocomplete/$'
      fullPath: '/places-autocomplete/$'
      preLoaderRoute: typeof PlacesAutocompleteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-card-icons/$': {
      id: '/payment-card-icons/$'
      path: '/payment-card-icons/$'
      fullPath: '/payment-card-icons/$'
      preLoaderRoute: typeof PaymentCardIconsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input-tag/$': {
      id: '/input-tag/$'
      path: '/input-tag/$'
      fullPath: '/input-tag/$'
      preLoaderRoute: typeof InputTagSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-onboard/$': {
      id: '/app-onboard/$'
      path: '/app-onboard/$'
      fullPath: '/app-onboard/$'
      preLoaderRoute: typeof AppOnboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSearchRoute: ApiSearchRoute,
  AppOnboardSplatRoute: AppOnboardSplatRoute,
  InputTagSplatRoute: InputTagSplatRoute,
  PaymentCardIconsSplatRoute: PaymentCardIconsSplatRoute,
  PlacesAutocompleteSplatRoute: PlacesAutocompleteSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
